name: Publish

on: push

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.1"
      - name: Perform compress
        shell: bash
        run: |
          cp -r _src/lua lua
          cd compress
          lua app.lua files_to_compress.dat
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: lua